package nova;

import java.io.IOException;
import java.util.ArrayList;

import command.Command;
import core.Parser;
import core.Storage;
import core.Ui;
import exception.NovaException;
import task.Deadline;
import task.Event;
import task.Task;
import task.TaskList;
import task.ToDo;

/**
 * Represents the result of executing a command.
 * <p>
 * Encapsulates the outcome of a command execution including whether
 * the application should exit and any affected tasks.
 * This class suggested and generated by GitHub Copilot, it helps to unify the return type of executeCommand() for
 * both CLI and GUI
 */
class CommandResult {
    final boolean shouldExit;
    final Task affectedTask;
    final ArrayList<Integer> foundIndexes;
    final String type;

    CommandResult(boolean shouldExit, Task affectedTask, ArrayList<Integer> foundIndexes, String type) {
        this.shouldExit = shouldExit;
        this.affectedTask = affectedTask;
        this.foundIndexes = foundIndexes;
        this.type = type;
    }
}

/**
 * The main entry point for the nova.Nova application.
 * <p>
 * It works with {@link Ui}, {@link Parser}, {@link TaskList},
 * and {@link Storage}, loads existing tasks on startup and runs a command loop
 * until the user exits.
 */
public class Nova {

    private final Storage storage;
    private final TaskList tasks;
    private final Ui ui;

    /**
     * Constructs a {@code nova.Nova} application instance.
     * <p>
     * Initializes the user interface and storage components, and attempts
     * to load existing tasks from the specified file path. If loading fails
     * due to an I/O error, an error message is displayed and the application
     * starts with an empty task list.
     *
     * @param filePath The file path used for loading and saving tasks.
     */
    public Nova(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);

        TaskList loaded;
        try {
            ArrayList<Task> loadedTasks = storage.loadTasks();
            loaded = new TaskList(loadedTasks);
        } catch (IOException e) {
            ui.showLoadingError();
            loaded = new TaskList();
        }
        tasks = loaded;
    }

    /**
     * Runs the main command loop of the application.
     * <p>
     * Displays a welcome message, then repeatedly reads user input,
     * parses it into a {@link Command}, and executes it until an exit
     * command is issued.
     * <p>
     * Any {@link NovaException} thrown during parsing or execution is
     * caught and shown to the user as an error message. Any {@link IOException}
     * related to loading or saving tasks is also caught and reported.
     */
    public void run() {
        ui.showWelcome();

        while (true) {
            String input = ui.readCommand();

            try {
                Command cmd = Parser.parse(input);
                CommandResult result = executeCommand(cmd);
                if (result.shouldExit) {
                    ui.showBye();
                    return;
                }
                displayCliResult(result);
            } catch (NovaException e) {
                ui.showError(e.getMessage());
            } catch (IOException e) {
                ui.showError("I couldn't save/load your tasks file.");
            }
        }
    }

    /**
     * Executes a command and returns the result.
     * <p>
     * This is the unified command execution method used by both CLI and GUI.
     * It performs the actual business logic without any UI concerns.
     *
     * @param cmd The command to execute.
     * @return A nova.CommandResult containing the outcome of the execution.
     * @throws NovaException If the command execution fails.
     * @throws IOException If file operations fail.
     */
    private CommandResult executeCommand(Command cmd) throws NovaException, IOException {
        switch (cmd.getType()) {
        case EXIT:
            return new CommandResult(true, null, null, "exit");
        case LIST:
            return new CommandResult(false, null, null, "list");
        case MARK: {
            Task t = markTask(cmd.getIndex());
            return new CommandResult(false, t, null, "mark");
        }
        case UNMARK: {
            Task t = unmarkTask(cmd.getIndex());
            return new CommandResult(false, t, null, "unmark");
        }
        case DELETE: {
            Task removed = deleteTask(cmd.getIndex());
            return new CommandResult(false, removed, null, "delete");
        }
        case TODO: {
            Task t = addTodo(cmd.getDescription());
            return new CommandResult(false, t, null, "todo");
        }
        case DEADLINE: {
            Task t = addDeadline(cmd.getDescription(), cmd.getBy());
            return new CommandResult(false, t, null, "deadline");
        }
        case EVENT: {
            Task t = addEvent(cmd.getDescription(), cmd.getFrom(), cmd.getTo());
            return new CommandResult(false, t, null, "event");
        }
        case FIND: {
            ArrayList<Integer> matches = tasks.findIndexes(cmd.getDescription());
            return new CommandResult(false, null, matches, "find");
        }
        default:
            throw unknownCommand();
        }
    }

    /**
     * Displays the result of a command execution in CLI format.
     *
     * @param result The command result to display.
     * @throws NovaException If displaying the result fails.
     */
    private void displayCliResult(CommandResult result) throws NovaException {
        switch (result.type) {
        case "list":
            ui.showListHeader();
            for (int i = 0; i < tasks.size(); i++) {
                ui.showListItem(i + 1, tasks.get(i).toString());
            }
            ui.showListFooter();
            try {
                save();
            } catch (IOException e) {
                ui.showError("I couldn't save your tasks file.");
            }
            break;
        case "mark":
            ui.showTaskMarked(result.affectedTask.toString());
            break;
        case "unmark":
            ui.showTaskUnmarked(result.affectedTask.toString());
            break;
        case "delete":
            ui.showTaskDeleted(result.affectedTask.toString(), tasks.size());
            break;
        case "todo":
        case "deadline":
        case "event":
            ui.showTaskAdded(result.affectedTask.toString(), tasks.size());
            break;
        case "find":
            ui.showFindHeader();
            for (int idx : result.foundIndexes) {
                ui.showListItem(idx + 1, tasks.get(idx).toString());
            }
            ui.showListFooter();
            break;
        default:
            // This should never happen if executeCommand() is correct
            throw new NovaException("Unknown command result type: " + result.type);
        }
    }

    private void save() throws IOException {
        storage.saveTasks(tasks.getTasks());
    }

    private Task markTask(int idx) throws IOException, NovaException {
        tasks.mark(idx);
        save();
        return tasks.get(idx);
    }

    private Task unmarkTask(int idx) throws IOException, NovaException {
        tasks.unmark(idx);
        save();
        return tasks.get(idx);
    }

    private Task deleteTask(int idx) throws IOException, NovaException {
        Task removed = tasks.remove(idx);
        save();
        return removed;
    }

    private Task addTodo(String desc) throws IOException, NovaException {
        Task t = new ToDo(desc);
        if (tasks.containsDuplicate(t)) {
            throw new NovaException("This task already exists in your list.");
        }
        tasks.add(t);
        save();
        return t;
    }

    private Task addDeadline(String desc, String by) throws IOException, NovaException {
        Task t = new Deadline(desc, by);
        if (tasks.containsDuplicate(t)) {
            throw new NovaException("This task already exists in your list.");
        }
        tasks.add(t);
        save();
        return t;
    }

    private Task addEvent(String desc, String from, String to) throws IOException, NovaException {
        Task t = new Event(desc, from, to);
        if (tasks.containsDuplicate(t)) {
            throw new NovaException("This task already exists in your list.");
        }
        tasks.add(t);
        save();
        return t;
    }

    private String formatListForGui() throws NovaException {
        StringBuilder sb = new StringBuilder("Here are the tasks in your list:\n");
        for (int i = 0; i < tasks.size(); i++) {
            sb.append(i + 1).append(". ").append(tasks.get(i)).append("\n");
        }
        return sb.toString().trim();
    }

    private String formatAddedForGui(Task t) {
        return "Got it. I've added this task:\n  " + t
                + "\nNow you have " + tasks.size() + " tasks in the list.";
    }

    private String formatMarkedForGui(Task t) {
        return "Nice! I've marked this task as done:\n  " + t;
    }

    private String formatUnmarkedForGui(Task t) {
        return "OK, I've marked this task as not done yet:\n  " + t;
    }

    private String formatDeletedForGui(Task removed) {
        return "Noted. I've removed this task:\n  " + removed
                + "\nNow you have " + tasks.size() + " tasks in the list.";
    }

    private String formatFindForGui(ArrayList<Integer> matches) throws NovaException {
        if (matches == null || matches.isEmpty()) {
            return "No matching tasks found.";
        }
        StringBuilder sb = new StringBuilder("Here are the matching tasks in your list:\n");
        for (int idx : matches) {
            sb.append(idx + 1).append(". ").append(tasks.get(idx)).append("\n");
        }
        return sb.toString().trim();
    }

    private NovaException unknownCommand() {
        return new NovaException("So sorry, I don't understand what that means.");
    }

    public String getResponse(String input) {
        try {
            Command cmd = Parser.parse(input);
            CommandResult result = executeCommand(cmd);
            return formatGuiResult(result);
        } catch (NovaException e) {
            return "OOPS!!! " + e.getMessage();
        } catch (IOException e) {
            return "I couldn't save/load your tasks file.";
        }
    }

    /**
     * Formats the result of a command execution for GUI display.
     *
     * @param result The command result to format.
     * @return A formatted string suitable for GUI display.
     * @throws NovaException If formatting fails.
     */
    private String formatGuiResult(CommandResult result) throws NovaException {
        switch (result.type) {
        case "exit":
            return "Bye. Hope to see you again soon!";
        case "list":
            return formatListForGui();
        case "mark":
            return formatMarkedForGui(result.affectedTask);
        case "unmark":
            return formatUnmarkedForGui(result.affectedTask);
        case "delete":
            return formatDeletedForGui(result.affectedTask);
        case "todo":
        case "deadline":
        case "event":
            return formatAddedForGui(result.affectedTask);
        case "find":
            return formatFindForGui(result.foundIndexes);
        default:
            return "Unknown command result type.";
        }
    }

    public static void main(String[] args) {
        new Nova("data/nova.txt").run();
    }
}

